services:

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hive-init:
    image: postgres:16
    depends_on:
      - db
    environment:
      PGPASSWORD: mypassword
    volumes:
      - ./hive-init-sql:/sql
    command: >
      sh -c "
        until pg_isready -h db -p 5432 -U myuser; do sleep 1; done;
        psql -h db -U myuser -d mydb -f /sql/create_tables.sql;
        psql -h db -U myuser -d mydb -f /sql/Security-tables.sql;
        psql -h db -U myuser -d mydb -f /sql/addusers.sql
      "

  hivemq:
    image: hivemq/hivemq4
    container_name: hivemq
    ports:
      - "1883:1883"    # MQTT
      - "8883:8883"    # mTLS MQTT
      - "1884:1884"    # MQTT with DB security 
      - "8080:8080"    # HiveMQ Control Center
      - "9399:9399"    # Prometheus metrics (extension)
      - "8888:8888"    # HiveMQ API
      - "9999:9999"    # HiveMQ x509 testport
    volumes:
      # - ./hivemq-data:/opt/hivemq/data
      - ./Hive-config:/opt/hivemq/conf
      - ./hivemq-prometheus-extension:/opt/hivemq/extensions/hivemq-prometheus-extension
      - ./hivemq-sparkplug-aware-extension:/opt/hivemq/extensions/hivemq-sparkplug-aware-extension
      - ./postgres-conf:/opt/hivemq/extensions/hivemq-postgresql-extension/conf
      - ./Hive-security-config:/opt/hivemq/extensions/hivemq-enterprise-security-extension/conf
      - ./kafka-config:/opt/hivemq/extensions/hivemq-kafka-extension/conf
      - ./hivemq-entrypoint.sh:/entrypoint.sh
    environment:
      HIVEMQ_LICENSE: ""
      POSTGRES_HOST: db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    depends_on:
      - db
      - hive-init
    restart: unless-stopped
    entrypoint: ["/entrypoint.sh"]


  hivemqedge:
    #image: hivemq/hivemq-edge:2026.3
    image: hivemq/hivemq-edge:latest

    container_name: hivemq-edge
    ports:
       - 2883:1883                     # MQTT/TCP protocol port
       - 2080:8080                     # HiveMQ Edge port
    #  - 2442:2442                     # MQTTSN
       - 2888:8888    # HiveMQ API
    volumes:
       - ./Hive-edge-config:/opt/hivemq/conf
    environment:
      HIVEMQ_LICENSE: ""
    restart: unless-stopped
    # entrypoint: ["/entrypoint.sh"]


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./Prometius-config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3010:3000"   # host 3000 er optaget af retool-onpremise-api paa dkretool
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./hivemq-grafana-dashboard-prometheus-4.json:/var/lib/grafana/dashboards/hivemq.json
      - ./sensor-grafana-dashboard-postgres.json:/var/lib/grafana/dashboards/sensor.json
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/hivemq.json
      - GF_SECURITY_ADMIN_USER=admin       # default username
      - GF_SECURITY_ADMIN_PASSWORD=admin   # default password
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_CHANGE=true
    depends_on:
      - db
      - hive-init
    restart: unless-stopped
  
  temp-simulator:
    image: python:3.12-slim
    container_name: temp-simulator
    depends_on:
      - hivemq
    environment:
      MQTT_HOST: hivemq
      MQTT_PORT: 1883
      MQTT_TOPIC: sensors/temperature
      MQTT_HOST_CLIENTID: Temp-simulator
      INTERVAL: 5
      PYTHONUNBUFFERED: 1
    command: >
      sh -c "pip install --upgrade pip &&pip install paho-mqtt  --root-user-action=ignore &&
             python3 /app/publisher.py"
    volumes:
      - ./temp-simulator:/app
    restart: unless-stopped


  Sparkplug-simulator:
    image: python:3.12-slim
    container_name: sparkplug-simulator
    depends_on:
      - hivemq
    environment:
      PYTHONUNBUFFERED: 1
    command: >
      sh -c "pip install --upgrade pip && pip install -r /app/requirements.txt --root-user-action=ignore &&
             python3 /app/genSP.py"
    volumes:
      - ./SparkPlug-sim:/app
    restart: unless-stopped

  MQTT_monitor:
    image: python:3.12-slim
    container_name: MQTT_monitor.py
    depends_on:
      - hivemq
    environment:
      PYTHONUNBUFFERED: 1
      MQTT_BROKER: "hivemq"
      MQTT_PORT: 1883
      MQTT_USER: "superuser"
      MQTT_PASS: "admin"
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install --upgrade pip && pip install -r /app/requirements.txt --root-user-action=ignore &&
             python3 /app/mqtt_monitor.py"
    volumes:
      - ./MQTT_monitor:/app
    restart: "no"



  OPCUA-simulator:
    image: python:3.12-slim
    container_name: opcua-simulator
    depends_on:
      - hivemq
    environment:
      PYTHONUNBUFFERED: 1
    command: >
      sh -c "pip install --upgrade pip &&pip install opcua --root-user-action=ignore &&
             python3 /app/OPCUA-server.py"
    volumes:
      - ./OPCUA-simulator:/app
    ports:
      - "4841:4841"
    restart: unless-stopped


  OPCUA-browser:
    image: iotechsys/opc-ua-browser
    container_name: opcua-browser
    depends_on:
      - hivemq
    environment:
      PYTHONUNBUFFERED: 1
    command: >
      sh -c "pip install --upgrade pip &&pip install opcua --root-user-action=ignore &&
             python3 /app/OPCUA-server.py"
    volumes:
      - ./OPCUA_Browser:/data 
    ports:
      - "2304:8080"
    restart: unless-stopped

  redpanda:
      image: docker.redpanda.com/redpandadata/redpanda:latest
      container_name: redpanda-0
      command:
        - redpanda
        - start
        - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
        # Address the broker advertises to clients that connect to the Kafka API.
        # Use the internal addresses to connect to the Redpanda brokers'
        # from inside the same Docker network.
        # Use the external addresses to connect to the Redpanda brokers'
        # from outside the Docker network.
        - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
        - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
        # Address the broker advertises to clients that connect to the HTTP Proxy.
        - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
        - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
        # Redpanda brokers use the RPC API to communicate with each other internally.
        - --rpc-addr redpanda-0:33145
        - --advertise-rpc-addr redpanda-0:33145
        # Mode dev-container uses well-known configuration properties for development in containers.
        - --mode dev-container
        # Tells Seastar (the framework Redpanda uses under the hood) to use 1 core on the system.
        - --smp 1
        - --default-log-level=info
      volumes:
        - redpanda-0:/var/lib/redpanda/data
      #networks:
      #  - redpanda_network
      ports:
        - 18081:18081
        - 18082:18082
        - 19092:19092
        - 19644:9644
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8099:8080"
    environment:
      KAFKA_BROKERS: "redpanda:9092"
      REDPANDA_BROKERS: "redpanda:9092"
    depends_on:
      - redpanda


# docker run -d -v <your_data_path>:/data --name opc-ua-browser -p 8080:8080 iotechsys/opc-ua-browser

volumes:
  postgres_data:
  grafana-storage:
  redpanda-0: null
